export type SttLanguage = { id: string; label: string; whisper?: string };

/** Whisper multilingual: ISO 639-1, plus auto-detect. */
export const STT_LANGUAGES: SttLanguage[] = [
  { id: 'auto', label: 'Auto' },
  { id: 'es', label: 'Español', whisper: 'spanish' },
  { id: 'en', label: 'English', whisper: 'english' },
  { id: 'pt', label: 'Português', whisper: 'portuguese' },
  { id: 'fr', label: 'Français', whisper: 'french' },
  { id: 'de', label: 'Deutsch', whisper: 'german' },
  { id: 'it', label: 'Italiano', whisper: 'italian' },
  { id: 'ca', label: 'Català', whisper: 'catalan' },
  { id: 'gl', label: 'Galego', whisper: 'galician' },
  { id: 'eu', label: 'Euskara', whisper: 'basque' },
  { id: 'nl', label: 'Nederlands', whisper: 'dutch' },
  { id: 'pl', label: 'Polski', whisper: 'polish' },
  { id: 'ru', label: 'Русский', whisper: 'russian' },
  { id: 'uk', label: 'Українська', whisper: 'ukrainian' },
  { id: 'zh', label: '中文', whisper: 'chinese' },
  { id: 'ja', label: '日本語', whisper: 'japanese' },
  { id: 'ko', label: '한국어', whisper: 'korean' },
  { id: 'ar', label: 'العربية', whisper: 'arabic' },
  { id: 'hi', label: 'हिन्दी', whisper: 'hindi' },
  { id: 'bn', label: 'বাংলা', whisper: 'bengali' },
  { id: 'ur', label: 'اردو', whisper: 'urdu' },
  { id: 'tr', label: 'Türkçe', whisper: 'turkish' },
  { id: 'vi', label: 'Tiếng Việt', whisper: 'vietnamese' },
  { id: 'th', label: 'ไทย', whisper: 'thai' },
  { id: 'id', label: 'Indonesia', whisper: 'indonesian' },
  { id: 'ms', label: 'Melayu', whisper: 'malay' },
  { id: 'tl', label: 'Filipino', whisper: 'tagalog' },
  { id: 'sv', label: 'Svenska', whisper: 'swedish' },
  { id: 'no', label: 'Norsk', whisper: 'norwegian' },
  { id: 'da', label: 'Dansk', whisper: 'danish' },
  { id: 'fi', label: 'Suomi', whisper: 'finnish' },
  { id: 'cs', label: 'Čeština', whisper: 'czech' },
  { id: 'sk', label: 'Slovenčina', whisper: 'slovak' },
  { id: 'hu', label: 'Magyar', whisper: 'hungarian' },
  { id: 'ro', label: 'Română', whisper: 'romanian' },
  { id: 'el', label: 'Ελληνικά', whisper: 'greek' },
  { id: 'he', label: 'עברית', whisper: 'hebrew' },
  { id: 'fa', label: 'فارسی', whisper: 'persian' },
  { id: 'ta', label: 'தமிழ்', whisper: 'tamil' },
  { id: 'te', label: 'తెలుగు', whisper: 'telugu' },
  { id: 'ml', label: 'മലയാളം', whisper: 'malayalam' },
  { id: 'kn', label: 'ಕನ್ನಡ', whisper: 'kannada' },
  { id: 'mr', label: 'मराठी', whisper: 'marathi' },
  { id: 'gu', label: 'ગુજરાતી', whisper: 'gujarati' },
  { id: 'pa', label: 'ਪੰਜਾਬੀ', whisper: 'punjabi' },
  { id: 'sw', label: 'Kiswahili', whisper: 'swahili' },
  { id: 'af', label: 'Afrikaans', whisper: 'afrikaans' },
  { id: 'hr', label: 'Hrvatski', whisper: 'croatian' },
  { id: 'sr', label: 'Српски', whisper: 'serbian' },
  { id: 'bg', label: 'Български', whisper: 'bulgarian' },
  { id: 'lt', label: 'Lietuvių', whisper: 'lithuanian' },
  { id: 'lv', label: 'Latviešu', whisper: 'latvian' },
  { id: 'et', label: 'Eesti', whisper: 'estonian' },
  { id: 'sl', label: 'Slovenščina', whisper: 'slovenian' },
];

export function whisperLanguage(id: string): string | undefined {
  return STT_LANGUAGES.find((item) => item.id === id)?.whisper;
}
